<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = [
            [
                'id' => 1,
                'parent_id' => 0,
                'name' => '后台首页',
                'url' => 'admin/index/index',
                'route_name' => 'admin.index.index',
                'icon' => 'fa-home',
                'is_show' => 1,
                'sort_id' => 99,
                'log_method' => '不记录',
            ], [
                'id' => 2,
                'parent_id' => 0,
                'name' => '达人管理',
                'url' => 'admin/customers/manage',
                'route_name' => '',
                'icon' => 'fa-user-circle-o',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ], [
                'id' => 3,
                'parent_id' => 0,
                'name' => '达人地址管理',
                'url' => 'admin/customer_addresses/index',
                'route_name' => 'admin.customer_addresses.index',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ], [
                'id' => 4,
                'parent_id' => 0,
                'name' => '产品管理',
                'url' => 'admin/products/index',
                'route_name' => 'admin.products.index',
                'icon' => 'fa-cubes',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ], [
                'id' => 5,
                'parent_id' => 0,
                'name' => '寄样管理',
                'url' => 'admin/send_samples/index',
                'route_name' => 'admin.send_samples.index',
                'icon' => 'fa-send',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 6,
                'parent_id' => 0,
                'name' => '数据统计',
                'url' => 'admin/statistics/sales',
                'route_name' => 'admin.statistics.sales',
                'icon' => 'fa-area-chart',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 7,
                'parent_id' => 0,
                'name' => '财务管理',
                'url' => 'admin/finances/manage',
                'route_name' => 'admin.finances.manage',
                'icon' => 'fa-cny',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 8,
                'parent_id' => 0,
                'name' => '系统管理',
                'url' => 'admin/sys',
                'route_name' => '',
                'icon' => 'fa-desktop',
                'is_show' => 1,
                'sort_id' => 1099,
                'log_method' => '不记录',
            ],[
                'id' => 20,
                'parent_id' => 2,
                'name' => '公海',
                'url' => 'admin/customers/index/1',
                'route_name' => 'admin.customers.index1',
                'icon' => 'fa-th',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 21,
                'parent_id' => 2,
                'name' => '跟进中',
                'url' => 'admin/customers/index/2',
                'route_name' => 'admin.customers.index2',
                'icon' => 'fa-calendar-check-o',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 22,
                'parent_id' => 2,
                'name' => '已跟进',
                'url' => 'admin/customers/index/3',
                'route_name' => 'admin.customers.index3',
                'icon' => 'fa-chain',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 23,
                'parent_id' => 2,
                'name' => '录入达人',
                'url' => 'admin/customers/add',
                'route_name' => 'admin.customers.add',
                'icon' => 'fa-plus',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 24,
                'parent_id' => 2,
                'name' => '修改达人',
                'url' => 'admin/customers/edit',
                'route_name' => 'admin.customers.edit',
                'icon' => 'fa-edit',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 25,
                'parent_id' => 2,
                'name' => '录入达人操作',
                'url' => 'admin/customers/create',
                'route_name' => 'admin.customers.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 26,
                'parent_id' => 2,
                'name' => '修改达人操作',
                'url' => 'admin/customers/update',
                'route_name' => 'admin.customers.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 27,
                'parent_id' => 2,
                'name' => '踢到公海',
                'url' => 'admin/customers/high_seas',
                'route_name' => 'admin.customers.high_seas',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 28,
                'parent_id' => 2,
                'name' => '跟进达人操作',
                'url' => 'admin/customers/follow_up',
                'route_name' => 'admin.customers.follow_up',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 29,
                'parent_id' => 2,
                'name' => '搜索',
                'url' => 'admin/customers/search',
                'route_name' => 'admin.customers.search',
                'icon' => 'fa-search',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 30,
                'parent_id' => 2,
                'name' => '销售额',
                'url' => 'admin/customer_sales/index',
                'route_name' => 'admin.customer_sales.index',
                'icon' => 'fa-list',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 40,
                'parent_id' => 5,
                'name' => '添加寄样',
                'url' => 'admin/send_samples/add',
                'route_name' => 'admin.send_samples.add',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 41,
                'parent_id' => 5,
                'name' => '寄样修改',
                'url' => 'admin/send_samples/edit',
                'route_name' => 'admin.send_samples.edit',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 42,
                'parent_id' => 5,
                'name' => '拒绝寄样申请',
                'url' => 'admin/send_samples/reject',
                'route_name' => 'admin.send_samples.reject',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 43,
                'parent_id' => 5,
                'name' => '寄样发货',
                'url' => 'admin/send_samples/send',
                'route_name' => 'admin.send_samples.send',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 44,
                'parent_id' => 5,
                'name' => '导入',
                'url' => 'admin/send_samples/import',
                'route_name' => 'admin.send_samples.import',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 45,
                'parent_id' => 5,
                'name' => '导出',
                'url' => 'admin/send_samples/export',
                'route_name' => 'admin.send_samples.export',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 46,
                'parent_id' => 5,
                'name' => '发货操作',
                'url' => 'admin/send_samples/do_send',
                'route_name' => 'admin.send_samples.do_send',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 47,
                'parent_id' => 5,
                'name' => '签收操作',
                'url' => 'admin/send_samples/sign',
                'route_name' => 'admin.send_samples.sign',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 50,
                'parent_id' => 4,
                'name' => '添加产品',
                'url' => 'admin/products/add',
                'route_name' => 'admin.products.add',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 51,
                'parent_id' => 4,
                'name' => '添加产品操作',
                'url' => 'admin/products/create',
                'route_name' => 'admin.products.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 52,
                'parent_id' => 4,
                'name' => '修改产品',
                'url' => 'admin/products/edit',
                'route_name' => 'admin.products.edit',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 53,
                'parent_id' => 4,
                'name' => '修改产品操作',
                'url' => 'admin/products/update',
                'route_name' => 'admin.products.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 54,
                'parent_id' => 4,
                'name' => '删除产品',
                'url' => 'admin/products/del',
                'route_name' => 'admin.products.del',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 60,
                'parent_id' => 3,
                'name' => '添加达人地址',
                'url' => 'admin/customer_addresses/add',
                'route_name' => 'admin.customer_addresses.add',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 61,
                'parent_id' => 3,
                'name' => '修改达人地址',
                'url' => 'admin/customer_addresses/edit',
                'route_name' => 'admin.customer_addresses.edit',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 62,
                'parent_id' => 3,
                'name' => '删除达人地址',
                'url' => 'admin/customer_addresses/del',
                'route_name' => 'admin.customer_addresses.del',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 70,
                'parent_id' => 7,
                'name' => '销售额管理',
                'url' => 'admin/customer_sales/manage',
                'route_name' => 'admin.customer_sales.manage',
                'icon' => 'fa-list',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 71,
                'parent_id' => 7,
                'name' => '销售额导入',
                'url' => 'admin/customer_sales/import',
                'route_name' => 'admin.customer_sales.import',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 72,
                'parent_id' => 7,
                'name' => '销售业绩',
                'url' => 'admin/customer_sales/performance',
                'route_name' => 'admin.customer_sales.performance',
                'icon' => 'fa-area-chart',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 80,
                'parent_id' => 8,
                'name' => '员工管理',
                'url' => 'admin/admin_user/index',
                'route_name' => 'admin.admin_user.index',
                'icon' => 'fa-user',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 81,
                'parent_id' => 88,
                'name' => '添加用户界面',
                'url' => 'admin/admin_user/add',
                'route_name' => 'admin.admin_user.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 82,
                'parent_id' => 88,
                'name' => '修改用户界面',
                'url' => 'admin/admin_user/edit',
                'route_name' => 'admin.admin_user.edit',
                'icon' => 'fa-edit',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 83,
                'parent_id' => 88,
                'name' => '删除用户',
                'url' => 'admin/admin_user/del',
                'route_name' => 'admin.admin_user.del',
                'icon' => 'fa-close',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 90,
                'parent_id' => 8,
                'name' => '角色管理',
                'url' => 'admin/admin_role/index',
                'route_name' => 'admin.admin_role.index',
                'icon' => 'fa-group',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 91,
                'parent_id' => 90,
                'name' => '添加角色界面',
                'url' => 'admin/admin_role/add',
                'route_name' => 'admin.admin_role.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 92,
                'parent_id' => 90,
                'name' => '修改角色界面',
                'url' => 'admin/admin_role/edit',
                'route_name' => 'admin.admin_role.edit',
                'icon' => 'fa-edit',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 93,
                'parent_id' => 90,
                'name' => '删除角色',
                'url' => 'admin/admin_role/del',
                'route_name' => 'admin.admin_role.del',
                'icon' => 'fa-close',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 94,
                'parent_id' => 90,
                'name' => '角色授权界面',
                'url' => 'admin/admin_role/access',
                'route_name' => 'admin.admin_role.access',
                'icon' => 'fa-key',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 100,
                'parent_id' => 8,
                'name' => '菜单管理',
                'url' => 'admin/admin_menu/index',
                'route_name' => 'admin.admin_menu.index',
                'icon' => 'fa-align-justify',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 101,
                'parent_id' => 100,
                'name' => '添加菜单界面',
                'url' => 'admin/admin_menu/add',
                'route_name' => 'admin.admin_menu.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 102,
                'parent_id' => 100,
                'name' => '修改菜单界面',
                'url' => 'admin/admin_menu/edit',
                'route_name' => 'admin.admin_menu.edit',
                'icon' => 'fa-edit',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 103,
                'parent_id' => 100,
                'name' => '删除菜单',
                'url' => 'admin/admin_menu/del',
                'route_name' => 'admin.admin_menu.del',
                'icon' => 'fa-close',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 110,
                'parent_id' => 8,
                'name' => '操作日志',
                'url' => 'admin/admin_log/index',
                'route_name' => 'admin.admin_log.index',
                'icon' => 'fa-keyboard-o',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 111,
                'parent_id' => 110,
                'name' => '查看操作日志详情',
                'url' => 'admin/admin_log/view',
                'route_name' => 'admin.admin_log.view',
                'icon' => 'fa-search-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 112,
                'parent_id' => 110,
                'name' => '个人资料',
                'url' => 'admin/admin_user/profile',
                'route_name' => 'admin.admin_user.profile',
                'icon' => 'fa-smile-o',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 120,
                'parent_id' => 8,
                'name' => '用户管理',
                'url' => 'admin/user/mange',
                'route_name' => '',
                'icon' => 'fa-users',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 121,
                'parent_id' => 120,
                'name' => '用户管理',
                'url' => 'admin/user/index',
                'route_name' => 'admin.user.index',
                'icon' => 'fa-user',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 122,
                'parent_id' => 120,
                'name' => '添加用户界面',
                'url' => 'admin/user/add',
                'route_name' => 'admin.user.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 123,
                'parent_id' => 120,
                'name' => '修改用户界面',
                'url' => 'admin/user/edit',
                'route_name' => 'admin.user.edit',
                'icon' => 'fa-pencil',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 124,
                'parent_id' => 120,
                'name' => '删除用户',
                'url' => 'admin/user/del',
                'route_name' => 'admin.user.del',
                'icon' => 'fa-trash',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 125,
                'parent_id' => 120,
                'name' => '启用用户',
                'url' => 'admin/user/enable',
                'route_name' => 'admin.user.enable',
                'icon' => 'fa-circle',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 126,
                'parent_id' => 120,
                'name' => '禁用用户',
                'url' => 'admin/user/disable',
                'route_name' => 'admin.user.disable',
                'icon' => 'fa-circle',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 130,
                'parent_id' => 8,
                'name' => '用户等级管理',
                'url' => 'admin/user_level/index',
                'route_name' => 'admin.user_level.index',
                'icon' => 'fa-th-list',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 131,
                'parent_id' => 130,
                'name' => '添加用户等级界面',
                'url' => 'admin/user_level/add',
                'route_name' => 'admin.user_level.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 132,
                'parent_id' => 130,
                'name' => '修改用户等级界面',
                'url' => 'admin/user_level/edit',
                'route_name' => 'admin.user_level.edit',
                'icon' => 'fa-pencil',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 133,
                'parent_id' => 130,
                'name' => '删除用户等级',
                'url' => 'admin/user_level/del',
                'route_name' => 'admin.user_level.del',
                'icon' => 'fa-trash',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 134,
                'parent_id' => 130,
                'name' => '启用用户等级',
                'url' => 'admin/user_level/enable',
                'route_name' => 'admin.user_level.enable',
                'icon' => 'fa-circle',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 135,
                'parent_id' => 130,
                'name' => '禁用用户等级',
                'url' => 'admin/user_level/disable',
                'route_name' => 'admin.user_level.disable',
                'icon' => 'fa-circle',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 140,
                'parent_id' => 8,
                'name' => '开发管理',
                'url' => 'admin/develop/manager',
                'route_name' => '',
                'icon' => 'fa-code',
                'is_show' => 0,
                'sort_id' => 1005,
                'log_method' => '不记录',
            ],[
                'id' => 141,
                'parent_id' => 140,
                'name' => '设置配置',
                'url' => 'admin/develop/setting',
                'route_name' => '',
                'icon' => 'fa-cogs',
                'is_show' => 1,
                'sort_id' => 995,
                'log_method' => '不记录',
            ],[
                'id' => 142,
                'parent_id' => 140,
                'name' => '设置管理',
                'url' => 'admin/setting/index',
                'route_name' => 'admin.setting.index',
                'icon' => 'fa-cog',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 143,
                'parent_id' => 140,
                'name' => '添加设置界面',
                'url' => 'admin/setting/add',
                'route_name' => 'admin.setting.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 144,
                'parent_id' => 140,
                'name' => '修改设置界面',
                'url' => 'admin/setting/edit',
                'route_name' => 'admin.setting.edit',
                'icon' => 'fa-pencil',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 145,
                'parent_id' => 140,
                'name' => '删除设置',
                'url' => 'admin/setting/del',
                'route_name' => 'admin.setting.del',
                'icon' => 'fa-trash',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 150,
                'parent_id' => 8,
                'name' => '设置分组管理',
                'url' => 'admin/setting_group/index',
                'route_name' => 'admin.setting_group.index',
                'icon' => 'fa-list',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 151,
                'parent_id' => 150,
                'name' => '添加设置分组界面',
                'url' => 'admin/setting_group/add',
                'route_name' => 'admin.setting_group.add',
                'icon' => 'fa-plus',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 152,
                'parent_id' => 150,
                'name' => '修改设置分组界面',
                'url' => 'admin/setting_group/edit',
                'route_name' => 'admin.setting_group.edit',
                'icon' => 'fa-pencil',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 153,
                'parent_id' => 150,
                'name' => '删除设置分组',
                'url' => 'admin/setting_group/del',
                'route_name' => 'admin.setting_group.del',
                'icon' => 'fa-trash',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 146,
                'parent_id' => 140,
                'name' => '设置中心',
                'url' => 'admin/setting/center',
                'route_name' => '',
                'icon' => 'fa-cogs',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 147,
                'parent_id' => 140,
                'name' => '所有配置',
                'url' => 'admin/setting/all',
                'route_name' => 'admin.setting.all',
                'icon' => 'fa-list',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 148,
                'parent_id' => 140,
                'name' => '后台设置',
                'url' => 'admin/setting/admin',
                'route_name' => 'admin.setting.admin',
                'icon' => 'fa-adjust',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 149,
                'parent_id' => 140,
                'name' => '更新设置',
                'url' => 'admin/setting/update',
                'route_name' => 'admin.setting.update',
                'icon' => 'fa-pencil',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 160,
                'parent_id' => 8,
                'name' => '数据维护',
                'url' => 'admin/database/table',
                'route_name' => 'admin.database.table',
                'icon' => 'fa-database',
                'is_show' => 1,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 161,
                'parent_id' => 160,
                'name' => '查看表详情',
                'url' => 'admin/database/view',
                'route_name' => 'admin.database.view',
                'icon' => 'fa-eye',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 162,
                'parent_id' => 160,
                'name' => '优化表',
                'url' => 'admin/database/optimize',
                'route_name' => 'admin.database.optimize',
                'icon' => 'fa-refresh',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 163,
                'parent_id' => 160,
                'name' => '修复表',
                'url' => 'admin/database/repair',
                'route_name' => 'admin.database.repair',
                'icon' => 'fa-circle-o-notch',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 127,
                'parent_id' => 120,
                'name' => '创建用户',
                'url' => 'admin/user/create',
                'route_name' => 'admin.user.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 128,
                'parent_id' => 120,
                'name' => '修改用户',
                'url' => 'admin/user/update',
                'route_name' => 'admin.user.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 84,
                'parent_id' => 88,
                'name' => '修改头像',
                'url' => 'admin/admin_user/update_avatar',
                'route_name' => 'admin.admin_user.update_avatar',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 85,
                'parent_id' => 88,
                'name' => '添加用户',
                'url' => 'admin/admin_user/create',
                'route_name' => 'admin.admin_user.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 86,
                'parent_id' => 88,
                'name' => '修改用户',
                'url' => 'admin/admin_user/update',
                'route_name' => 'admin.admin_user.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 87,
                'parent_id' => 88,
                'name' => '用户启用',
                'url' => 'admin/admin_user/enable',
                'route_name' => 'admin.admin_user.enable',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 88,
                'parent_id' => 88,
                'name' => '用户禁用',
                'url' => 'admin/admin_user/disable',
                'route_name' => 'admin.admin_user.disable',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 89,
                'parent_id' => 88,
                'name' => '修改昵称',
                'url' => 'admin/admin_user/update_nickname',
                'route_name' => 'admin.admin_user.update_nickname',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 901,
                'parent_id' => 88,
                'name' => '修改密码',
                'url' => 'admin/admin_user/update_password',
                'route_name' => 'admin.admin_user.update_password',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 95,
                'parent_id' => 90,
                'name' => '创建角色',
                'url' => 'admin/admin_role/create',
                'route_name' => 'admin.admin_role.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 96,
                'parent_id' => 90,
                'name' => '修改角色',
                'url' => 'admin/admin_role/update',
                'route_name' => 'admin.admin_role.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 97,
                'parent_id' => 90,
                'name' => '启用角色',
                'url' => 'admin/admin_role/enable',
                'route_name' => 'admin.admin_role.enable',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 98,
                'parent_id' => 90,
                'name' => '禁用角色',
                'url' => 'admin/admin_role/disable',
                'route_name' => 'admin.admin_role.disable',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 99,
                'parent_id' => 90,
                'name' => '角色授权',
                'url' => 'admin/admin_role/access_operate',
                'route_name' => 'admin.admin_role.access_operate',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 104,
                'parent_id' => 100,
                'name' => '创建菜单',
                'url' => 'admin/admin_menu/create',
                'route_name' => 'admin.admin_menu.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 105,
                'parent_id' => 100,
                'name' => '修改菜单',
                'url' => 'admin/admin_menu/update',
                'route_name' => 'admin.admin_menu.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 1461,
                'parent_id' => 140,
                'name' => '创建设置',
                'url' => 'admin/setting/create',
                'route_name' => 'admin.setting.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 1471,
                'parent_id' => 140,
                'name' => '修改设置',
                'url' => 'admin/setting/do_update',
                'route_name' => 'admin.setting.do_update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 1481,
                'parent_id' => 140,
                'name' => '修改设置',
                'url' => 'admin/setting/info',
                'route_name' => 'admin.setting.info',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 154,
                'parent_id' => 150,
                'name' => '创建设置分组',
                'url' => 'admin/setting_group/create',
                'route_name' => 'admin.setting_group.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 155,
                'parent_id' => 150,
                'name' => '修改设置',
                'url' => 'admin/setting_group/update',
                'route_name' => 'admin.setting_group.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 156,
                'parent_id' => 150,
                'name' => '生成菜单',
                'url' => 'admin/setting_group/menu',
                'route_name' => 'admin.setting_group.menu',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 157,
                'parent_id' => 150,
                'name' => '生成文件',
                'url' => 'admin/setting_group/file',
                'route_name' => 'admin.setting_group.file',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 129,
                'parent_id' => 120,
                'name' => '导出用户',
                'url' => 'admin/user/export',
                'route_name' => 'admin.user.export',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],[
                'id' => 136,
                'parent_id' => 130,
                'name' => '创建用户等级',
                'url' => 'admin/user_level/create',
                'route_name' => 'admin.user_level.create',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 137,
                'parent_id' => 130,
                'name' => '更新用户等级',
                'url' => 'admin/user_level/update',
                'route_name' => 'admin.user_level.update',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => 'POST',
            ],[
                'id' => 138,
                'parent_id' => 130,
                'name' => '用户等级导出',
                'url' => 'admin/user_level/export',
                'route_name' => 'admin.user_level.export',
                'icon' => 'fa-list',
                'is_show' => 0,
                'sort_id' => 1000,
                'log_method' => '不记录',
            ],
        ];
        DB::table('admin_menu')->insert($arr);
    }
}
